### PR TITLE
Added files for boiler plant system

### PR DESCRIPTION
**Pull request by karthikeyad-pnnl**
@mwetter : I am submitting this PR to add the boiler plant files to the case study package. I have added a validation file for the boiler plant system. However, I am still in the process of running the unit tests since I have to set up the environment on my new system.

I was planning to raise a separate issue and PR on the Buildings library repo to make the necessary changes so that the boiler plant system receives the required inputs from the AHU system.

Also, what do you think would be the best way to get the boiler plant controller files on to the package, since I am currently referencing the packages on my development branch on my forked repo?

Thanks,
Karthik

### CODE REVIEW

**Comment by mwetter** [comment]
@karthikeyad-pnnl : Thanks for the PR, I will look at it in the next few days.
Regarding the boiler plant control sequences, best would be if you can copy the package from your Buildings Library branch to the package `SystemModel.BoilerPlant.Controls` (or similar). If you automate the copying with a shell script, you can make any bug fixes, if needed, on your Buildings repo branch and update the copy in `SystemModel.BoilerPlant.Controls` so you have only one place where changes need to be implemented.

**Comment by mwetter** [comment]
@karthikeyad-pnnl : Can you please address or clarify these points:
- [ ] In `BoilerPlant`, there is an instance of `Modelica.Fluid.Pipes.DynamicPipe`. This introduces a static height difference which is physically not correct (as the boiler loop is a closed system). Also, we typically don't use this as it is a rather complex model.
- [ ] - [ ] In `BoilerPlant`, the pump has a rise time of 1 second, and the valves have a rise time of 120 seconds. Please ensure that the pump never works against a (almost fully) closed valve. Otherwise, because the pump forces the flow rate, the model will have huge pressure raises and associated pump power use.
- [ ] Please address the various warnings when simulating (or translating) the model (e.g., missing `each`, missing `outer` which is probably not needed when you remove the pipe)
- [ ] `ZoneModel_simplified` and `BoilerPlant` should not extend from `Modelica.Icons.Example` I believe because I don't think this model is meant to run by its own.
- [ ] Declare units and add comments, such as in `parameter Real boiDesCap = 4359751.36;`

**Comment by karthikeyad-pnnl** [comment]
@mwetter : Thank you for the feedback! I have currently addressed most of the points. Here are my comments about some of the points above.

- We added the dynamic pipe object to represent thermal loss to the envelope and outdoor air. We noticed that there was barely any time required for the hot water to reach supply temperature setpoint when the plant was started up, which would not be the case in actual systems where the hot water would have cooled down during off-cycle hours. Therefore, we decided to add the dynamic pipe to the model since all the other connections are adiabatic. Please let me know if I should still remove it, in case the above is not a major consideration to be made for the case study or if it will slow the simulation speed too much.
- The RP-1711 control sequence ensures that the pump is started only when the isolation valve for the boiler is open > 97.5% and is turned off otherwise. This should make sure the pump doesn't operate when the isolation valve has a small opening.
- I was able to resolve most of the warnings during compilation. However, there are some persistent warnings related to the initial conditions not being defined. I have tried resolving these by assigning the relevant parameter values, but that has not resolved the issue.
- I am yet to copy the boiler plant controller modules to the package. I will do so ASAP.

Thanks,
Karthik

**Comment by karthikeyad-pnnl** [comment]
@mwetter Hi Michael, 
I apologize for the delay in informing you. I have added the boiler plant controller models to the package. This PR is ready for review.
Thanks,
Karthik

**Comment by mwetter** [comment]
@karthikeyad-pnnl : Does this command work for you:
```
simulateModel("SystemModel.BoilerPlant.Validation.System", startTime=0, stopTime=172800, method="Cvode", tolerance=1e-06, resultFile="BoilerSystem");
```
I get 18 errors with Dymola 2022 and the Modelica Buildings Library, commit 03be4830c827f5d9609302a33adc6220fdf8972e (see `install.sh`)

Also, you do need to set `height_ab = 0` in the pipe from the MSL, otherwise the system won't be like a closed circuit where the height of supply and return pipes are canceling.

**Pull request merged**
