### PR TITLE
Issue92 case study full hvac

### PR DESCRIPTION
**Pull request by karthikeyad-pnnl**
@mwetter : I am submitting this PR to address some of the feedback you had provided during the OBC meeting on Monday. I have changed the input names for receiving requests for the boiler plant, as well as their associated comments, to make them more self-explanatory. I have also added a class at `SystemModel.VAV.PlantRequests`(that @JayHuLBL had implemented in branch for issue [1913](https://github.com/lbl-srg/modelica-buildings/tree/issue1913_g36_final)) for generating requests from multi-zone VAV AHUs to the `SystemModel.VAV` package, and added an instance of it to the `SystemModel.VAV.Guideline36` class. I have updated the unit test results with new variable names in the `SystemModel.BoilerPlant` package. I was unable to run unit tests on `SystemModel.Validation.System`, which kept failing with an error I couldn't understand. However, the model was translating and simulating properly when I used the "Simulate and plot" command in Dymola. I have attached the error log for that model.

[failed-simulator-dymola.log](https://github.com/lbl-srg/obc/files/8720818/failed-simulator-dymola.log)

### CODE REVIEW

**Comment by mwetter** [comment]
This contains the changes from https://github.com/lbl-srg/obc/issues/121#issuecomment-1134914204

**Comment by mwetter** [comment]
@karthikeyad-pnnl : Your log file has
```
/usr/bin/ld:/tmp/_obc_caseStudy_full_install/modelica-buildings/Buildings/Resources/Library/linux64/libModelicaBuildingsEnergyPlus_9_6_0.so: file format not recognized; treating as linker script
/usr/bin/ld:/tmp/_obc_caseStudy_full_install/modelica-buildings/Buildings/Resources/Library/linux64/libModelicaBuildingsEnergyPlus_9_6_0.so:1: syntax error
```
This is typically the case if the file is not downloaded, such as due to git-lfs not being installed on your computer, or if you compile for 32 bit instead of 64 bit. My guess is that it is the former reason.

**Comment by karthikeyad-pnnl** [comment]
> @karthikeyad-pnnl : Your log file has
> 
> ```
> /usr/bin/ld:/tmp/_obc_caseStudy_full_install/modelica-buildings/Buildings/Resources/Library/linux64/libModelicaBuildingsEnergyPlus_9_6_0.so: file format not recognized; treating as linker script
> /usr/bin/ld:/tmp/_obc_caseStudy_full_install/modelica-buildings/Buildings/Resources/Library/linux64/libModelicaBuildingsEnergyPlus_9_6_0.so:1: syntax error
> ```
> 
> This is typically the case if the file is not downloaded, such as due to git-lfs not being installed on your computer, or if you compile for 32 bit instead of 64 bit. My guess is that it is the former reason.

@mwetter : Oh ok. Will take a look at it. Thanks Michael!

**Comment by karthikeyad-pnnl** [comment]
@mwetter : I was able to resolve the failing unit test by removing and re-installing the temp folder with the Buildings library and BuildingsPy. The PR is now ready for review. Thanks!

**Pull request merged**
