### PR TITLE
Added the capability to plot cases as subplots

### PR DESCRIPTION
**Pull request by milicag**
This addresses #21. The code is added to the existing notebook.

### CODE REVIEW

**Comment by milicag** [comment]
@mwetter Here it is, sorry for the previous PR, I had some issues with Git which I've managed to resolve. I'm noticing some additional plotting capability in this notebook, should I add the case based plots to flow plotting etc?

**Comment by milicag** [comment]
Oh, I see, you'd like all the old 3x plotting fuctions to get *replaced* with the 2x? I'll do that first thing on Monday.

**Comment by mwetter** [comment]
@milicag Yes, please replace the 3x plots with the 2x plots. I still wonder how to safe some spaces so that we don't have too many pages full of plots. An option could be to use a 2x3 grid, see also https://www.python-course.eu/matplotlib_multiple_figures.php

**Comment by milicag** [comment]
I was thinking of that as well - one could drop 2 of these 2x on a single page, with captions, if nothing else. I'll attempt a 6 row grid with extra space between seasons (the iterator would know) and we can see if we like it.

**Comment by mwetter** [comment]
@milicag : We could also plot the 3 seasons on the same x-axis, and break the x-axis (see https://stackoverflow.com/questions/32185411/break-in-x-axis-of-matplotlib). If space is an issue, we could select fewer days in the plot, as long as we have the extremes and some diversity.

**Comment by milicag** [comment]
Neat, although potentially crowded. It may be nicer if we have 3 groups of 2, where the 2 are aligned without space so that only the lower one needs annotation on the x axis. That way we could fit all 6 in a fairly transparent way. It would be nice to have all seasons and cases on a single page.

**Pull request merged**
