### PR TITLE
Issue83 point list

### LINKED ISSUE #83: Add point list specification
This issue is to specify how to use vendor annotation for developing sequences in order to generate point list table.

### PR DESCRIPTION
**Pull request by JayHuLBL**
This closes #83.

- [x] added specification of how point list being generated

### CODE REVIEW

**Comment by mwetter** [comment]
@JayHuLBL : Thanks for the PR. I revised the wording, and added a "todo". Can you please make a proposal for how to address this "todo".

**Comment by JayHuLBL** [comment]
@mwetter 
Please see the updated specification regarding the point type propagation.

**Comment by mwetter** [comment]
@JayHuLBL : Can you please review my revisions and then we can discuss in our next meeting. I think the propagation rules became clearer this way. See also the comments in bold font for further suggested edits.

**Review by mwetter — COMMENTED** [review]
See comment https://github.com/lbl-srg/obc/pull/86#issuecomment-737621671

**Comment by JayHuLBL** [comment]
@mwetter I cleaned up the specification and left two comments.

**Comment by mwetter** [comment]
@JayHuLBL : Thanks for adding the need of multiple propagation declarations. Can you please see my revisions. I selected to allow multiple instances of `propagate` rather than an array in `instance`, and this will make it easier to change the value (if we had arrays, then a user would need to move items out the array and into another array). It will also avoid having to declare an array of only one element, which would probably be needed in many cases.

What remains to be done is to explain what the value of `controlledDevice="Terminal unit"` is, and how this is used. Currently, it is not used anywhere in the text and also not explained. Can you please address this so that all terms are explained, and only introduced if we need them.

**Pull request merged**
